/**
 * Typed shapes for the PortPilot HTTP API contract (docs/api/CONTRACT.md).
 * Field names mirror the dataclasses in src/portpilot/core/models.py exactly
 * (snake_case, as emitted by `to_doc()`). This file is generated by hand from
 * the frozen contract -- keep it in lockstep with CONTRACT.md, never ahead of it.
 */

export type RunStatus = "queued" | "running" | "paused" | "completed" | "failed" | "cancelled";

export type StepStatus =
  | "planned"
  | "selecting_tools"
  | "running"
  | "verifying"
  | "reflecting"
  | "done"
  | "failed"
  | "skipped";

export type ToolStatus = "draft" | "candidate" | "active" | "deprecated" | "rejected";

export type KnowledgeKind = "lesson" | "gotcha" | "memory" | "tool_card" | "run_digest";

export type SearchMode = "hybrid" | "vector" | "text";

export type EventType =
  | "run_created"
  | "lease_acquired"
  | "resumed"
  | "paused"
  | "cancelled"
  | "completed"
  | "failed"
  | "survey_done"
  | "plan_created"
  | "plan_revised"
  | "step_planned"
  | "step_started"
  | "step_verified"
  | "step_failed"
  | "tools_selected"
  | "tool_loaded"
  | "tool_call"
  | "tool_result"
  | "tool_error"
  | "tool_created"
  | "tool_validated"
  | "tool_promoted"
  | "tool_rejected"
  | "tool_deprecated"
  | "cli_checked"
  | "cli_installed"
  | "cli_refused"
  | "compaction"
  | "checkpoint"
  | "lesson_recorded"
  | "gotcha_recorded"
  | "budget_exceeded"
  | "note";

export interface Budgets {
  max_steps: number;
  max_tokens: number;
  max_minutes: number;
  max_tools_created: number;
  max_selected_tools: number;
  max_mid_step_loads: number;
}

export interface Usage {
  input_tokens: number;
  output_tokens: number;
  model_calls: number;
  tool_calls: number;
  compactions: number;
}

export interface Lease {
  owner: string;
  expires_at: string;
}

export interface Run {
  run_id: string;
  repo_url: string;
  goal: string;
  status: RunStatus;
  current_step_id: string | null;
  ltp_version: number;
  lease: Lease | null;
  budgets: Budgets;
  usage: Usage;
  cli_manifest: Array<{ name: string; version: string }>;
  tool_pins: Record<string, number>;
  control: string | null;
  error: string | null;
  workspace_branch: string;
  created_at: string;
  updated_at: string;
}

export interface RunSummary {
  run_id: string;
  repo_url: string;
  goal: string;
  status: RunStatus;
  created_at: string;
  updated_at: string;
  steps_total: number;
  steps_done: number;
  current_step_title: string | null;
  usage: Usage;
}

export interface Phase {
  id: string;
  title: string;
  goal: string;
  exit_criteria: string[];
  modules: string[];
}

export interface LongTermPlan {
  run_id: string;
  version: number;
  goal: string;
  phases: Phase[];
  assumptions: string[];
  rationale: string;
  created_at: string;
}

export interface Check {
  name: string;
  command: string;
  expect_exit: number;
  timeout_s: number;
}

export interface StepBudget {
  max_turns: number;
  max_tokens: number;
  max_minutes: number;
}

export interface ToolPick {
  name: string;
  version: number;
  reason: string;
  used: boolean;
  helpful: boolean | null;
}

export interface ShortTermPlan {
  step_id: string;
  run_id: string;
  seq: number;
  phase_id: string;
  title: string;
  objective: string;
  inputs: string[];
  acceptance: Check[];
  capability_hints: string[];
  budget: StepBudget;
  status: StepStatus;
  selected_tools: ToolPick[];
  missing_capabilities: string[];
  attempts: number;
  commit_sha: string | null;
  outcome: string | null;
  usage: Usage;
  started_at: string | null;
  ended_at: string | null;
}

export interface Event {
  run_id: string;
  seq: number;
  ts: string;
  type: EventType;
  step_id: string | null;
  payload: Record<string, unknown>;
}

export interface ArtifactMeta {
  artifact_id: string;
  run_id: string;
  step_id: string | null;
  kind: string;
  name: string;
  created_at: string;
}

export interface Artifact extends ArtifactMeta {
  content: string;
}

export interface ToolProvenance {
  run_id: string | null;
  step_id: string | null;
  repo_url: string | null;
  parent_version: number | null;
  author: "agent" | "seed";
}

export interface ToolStats {
  uses: number;
  successes: number;
  failures: number;
  runs_used_in: string[];
}

export interface ToolSummary {
  name: string;
  version: number;
  status: ToolStatus;
  description: string;
  when_to_use: string;
  tags: string[];
  requires_cli: string[];
  stats: ToolStats;
  provenance: ToolProvenance;
  created_at: string;
  versions_count: number;
}

export interface ToolRecord {
  name: string;
  version: number;
  description: string;
  when_to_use: string;
  input_schema: Record<string, unknown>;
  output_schema: Record<string, unknown>;
  files: Record<string, string>;
  tests: Record<string, string>;
  requires_cli: string[];
  tags: string[];
  status: ToolStatus;
  provenance: ToolProvenance;
  stats: ToolStats;
  created_at: string;
}

export interface KnowledgeSource {
  run_id: string | null;
  step_id: string | null;
  repo_url: string | null;
}

export interface KnowledgeItem {
  id: string;
  kind: KnowledgeKind;
  title: string;
  body: string;
  tags: string[];
  facets: Record<string, string>;
  sources: KnowledgeSource[];
  seen_count: number;
  status: string;
  ref: string | null;
  created_at: string;
  updated_at: string;
}

export interface Hit {
  item: KnowledgeItem;
  score: number;
  via: "vector" | "text" | "both";
}

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
  };
}

// ---------------------------------------------------------------- requests

export interface CreateRunRequest {
  repo_url: string;
  goal: string;
  budgets?: Partial<Budgets>;
}

export interface CreateRunResponse {
  run_id: string;
}

export interface ListRunsResponse {
  runs: RunSummary[];
}

export interface GetRunResponse {
  run: Run;
  plan: LongTermPlan | null;
  steps: ShortTermPlan[];
}

export interface GetStepResponse {
  step: ShortTermPlan;
}

export interface GetEventsResponse {
  events: Event[];
  next_after_seq: number;
}

export interface RunControlResponse {
  ok: true;
  status: RunStatus;
}

export interface GetArtifactsResponse {
  artifacts: ArtifactMeta[];
}

export interface GetArtifactResponse {
  artifact: Artifact;
}

export interface ListToolsResponse {
  tools: ToolSummary[];
}

export interface GetToolResponse {
  name: string;
  versions: ToolRecord[];
}

export interface SearchKnowledgeResponse {
  hits: Hit[];
}

export interface ListKnowledgeResponse {
  items: KnowledgeItem[];
}

// ------------------------------------------------------------ event payloads

export interface RunCreatedPayload {
  repo_url: string;
  goal: string;
}

export interface SurveyDonePayload {
  languages: Record<string, number>;
  files: number;
  dockerfiles: string[];
  artifact_id: string;
}

export interface PlanCreatedPayload {
  version: number;
  phases: Array<{ id: string; title: string }>;
  reason?: string;
}

export interface StepPlannedPayload {
  step_id: string;
  seq: number;
  title: string;
  phase_id: string;
}

export interface StepStartedPayload {
  seq: number;
  title: string;
  attempt: number;
}

export interface ToolsSelectedPayload {
  candidates: Array<{ name: string; version: number; score: number }>;
  picks: Array<{ name: string; version: number; reason: string }>;
  missing: string[];
  core_tools: string[];
  tool_schema_tokens: number;
}

export interface ToolLoadedPayload {
  name: string;
  version: number;
  reason: string;
}

export interface ToolCallPayload {
  tool: string;
  args_preview: string;
}

export interface ToolResultPayload {
  tool: string;
  ok: boolean;
  seconds: number;
  preview: string;
  artifact_id?: string;
}

export interface ToolErrorPayload {
  tool: string;
  error: string;
}

export interface ToolCreatedPayload {
  name: string;
  version: number;
  purpose: string;
}

export interface ToolValidatedPayload {
  name: string;
  version: number;
  ok: boolean;
  checks: Array<{ name: string; ok: boolean }>;
}

export interface ToolPromotedPayload {
  name: string;
  version: number;
  previous_active: number | null;
}

export interface ToolRejectedPayload {
  name: string;
  version: number;
  reason: string;
}

export interface CliCheckedPayload {
  installed: Record<string, string>;
  arch: string;
}

export interface CliInstalledPayload {
  name: string;
  version: string;
  already_installed: boolean;
}

export interface CliRefusedPayload {
  name: string;
  reason: string;
}

export interface CompactionPayload {
  tokens_before: number;
  tokens_after: number;
  messages_before: number;
  messages_after: number;
}

export interface CheckpointPayload {
  step_id: string;
  commit_sha: string;
}

export interface StepVerifiedPayload {
  ok: boolean;
  checks: Array<{ name: string; ok: boolean; exit_code: number }>;
}

export interface StepFailedPayload {
  reason: string;
  attempt: number;
}

export interface LessonRecordedPayload {
  item_id: string;
  title: string;
  merged: boolean;
}

export interface BudgetExceededPayload {
  budget: string;
  used: number;
  limit: number;
}

export interface TerminalPayload {
  reason?: string;
}
